# Generated by Django 4.2.5 on 2023-09-23 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0010_alter_myuser_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='sex',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='my_auth.sex'),
        ),
    ]
