# Generated by Django 4.2.5 on 2023-09-27 15:21

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0012_alter_myuser_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='username'),
        ),
    ]
