# Generated by Django 4.2.5 on 2023-09-29 16:58

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0013_alter_myuser_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'ordering': ('-is_superuser', '-is_active'), 'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='foto',
        ),
        migrations.AddField(
            model_name='myuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='телефон'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile/users', verbose_name='фотография'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='surname',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='отчество'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='city',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='электронная почта'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='sex',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='my_auth.sex', verbose_name='пол'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='username', verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=25, unique=True, verbose_name='никнейм'),
        ),
    ]
