# Generated by Django 4.2.5 on 2023-09-30 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0014_alter_myuser_options_remove_myuser_foto_myuser_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
            ],
        ),
    ]
