# Generated by Django 4.2.5 on 2023-09-20 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('quantity', models.IntegerField(default=0, verbose_name='количество')),
                ('icon', models.CharField(max_length=25, verbose_name='иконка')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='It_Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('pubhouse', models.CharField(max_length=50, verbose_name='издательство')),
                ('year', models.IntegerField(verbose_name='год')),
                ('book_id', models.IntegerField(verbose_name='id')),
                ('isbn', models.CharField(max_length=50, verbose_name='isbn')),
                ('pages', models.IntegerField(verbose_name='страниц')),
                ('dimension', models.CharField(max_length=25, verbose_name='размеры')),
                ('weight', models.IntegerField(verbose_name='вес')),
                ('authors', models.CharField(max_length=250, verbose_name='автор(ы)')),
                ('artists', models.CharField(max_length=100, verbose_name='художник(и)')),
                ('price', models.IntegerField(verbose_name='цена')),
                ('icon', models.CharField(max_length=50, verbose_name='обложка')),
                ('book_foto', models.CharField(max_length=100, verbose_name='фото')),
                ('demo_pdf', models.CharField(max_length=50, verbose_name='демо')),
                ('quantity', models.IntegerField(default=100, verbose_name='количество')),
                ('available', models.BooleanField(default=True, verbose_name='доступность')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.categories')),
            ],
            options={
                'verbose_name': 'книга',
                'verbose_name_plural': 'книги',
            },
        ),
    ]
