# Generated by Django 4.2.5 on 2023-09-21 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='it_book',
            name='category',
        ),
        migrations.RemoveField(
            model_name='it_book',
            name='slug',
        ),
    ]
