# Generated by Django 4.2.5 on 2023-09-21 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_it_book_category_remove_it_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='it_book',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='shop.categories'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=50, verbose_name='название'), max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
