# Generated by Django 4.2.5 on 2023-09-30 16:31

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_categories_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='categories', verbose_name='icons'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', verbose_name='URL'),
        ),
    ]
