# Generated by Django 4.2.5 on 2023-10-07 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_categories_icon_alter_categories_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='it_book',
            name='book_foto',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='it_book',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='it_books/img', verbose_name='обложка'),
        ),
        migrations.CreateModel(
            name='More_Photo_It_books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='profile/users', verbose_name='картинка')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.it_book')),
            ],
        ),
    ]
