# Generated by Django 4.2.5 on 2023-10-07 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_it_book_book_foto_alter_it_book_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='it_book',
            name='book_foto',
        ),
    ]
