# Generated by Django 4.2.5 on 2023-10-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_it_book_demo_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='it_book',
            name='demo_pdf',
            field=models.ImageField(blank=True, null=True, upload_to='it_books/pdf', verbose_name='demo'),
        ),
    ]
